export const imageUploadLabels = {
	choose: 'Choose an image',
	empty: 'Choose an image or drop it here.',
	crop: 'Crop preview',
	zoom: 'Zoom',
	rotation: 'Rotation',
	left: 'Rotate left',
	right: 'Rotate right',
	x: 'Horizontal position',
	y: 'Vertical position',
	aspect: 'Aspect ratio',
	original: 'Original',
	width: 'Output width',
	format: 'Format',
	quality: 'Quality',
	apply: 'Apply image',
	clear: 'Remove image',
	reset: 'Reset edits',
	loading: 'Loading image…',
	processing: 'Processing image…',
	source: 'Source',
	output: 'Output',
	required: 'required',
	pending: 'Apply your edits before submitting.',
	instructions:
		'Drag to position. Use arrow keys or the position sliders for precise adjustments.',
	limits: 'Input limit',
	outputLimit: 'Output limit',
	typeError: 'Choose a supported PNG, JPEG, or WebP image.',
	sizeError: 'The selected file exceeds the input size limit.',
	dimensionError: 'The image dimensions are outside the allowed limits.',
	decodeError: 'This file could not be decoded as an image.',
	encodeError: 'The image could not be exported in this format.',
	outputError: 'The result exceeds the output size limit. Reduce its dimensions or quality.',
	multipleError: 'Choose one image at a time.',
} as const;

export type ImageUploadLabels = { [Key in keyof typeof imageUploadLabels]: string };
