export const styles = {
	imageUpload: {
		base: 'w-full min-w-0 gap-4',
		drop: 'border border-dashed border-border bg-base-200 p-4 space-y-3',
		dragging: 'border-primary bg-primary-soft',
		editor: 'grid min-w-0 gap-6 md:grid-cols-[minmax(0,1fr)_16rem]',
		canvas: 'block w-full touch-none cursor-move rounded-box border border-border bg-base-300',
		controls: 'grid content-start gap-2 min-w-0',
		meta: 'font-mono text-xs text-muted break-words',
		error: 'text-sm text-error',
	},
	codeblock: {
		base: String.raw`block w-full min-w-0 bg-base-300 [&_.hljs]:text-xs [&_.hljs-keyword]:text-primary [&_.hljs-operator]:text-primary [&_.hljs-built\_in]:text-primary [&_.hljs-meta]:text-primary [&_.hljs-string]:text-success [&_.hljs-attr]:text-success [&_.hljs-number]:text-accent [&_.hljs-literal]:text-accent [&_.hljs-variable]:text-accent [&_.hljs-symbol]:text-accent [&_.hljs-subst]:text-base-content [&_.hljs-title]:text-secondary [&_.hljs-function]:text-secondary [&_.hljs-comment]:text-neutral-content [&_.hljs-comment]:opacity-60`,
		filename: 'border-base-200 border-b px-4 py-2 font-mono text-xs break-all',
		lines: '[--padding-right:0]',
		copy: '[--copy-border-radius:var(--radius-field)] [--copy-background:var(--color-base-200)] [--copy-color:var(--color-base-content)]',
	},
	focus: 'focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-focus focus-visible:outline-offset-4',
	tooltip: 'tooltip',
	field: {
		base: 'fieldset',
		legend: 'fieldset-legend',
		label: 'label flex items-center gap-2',
		note: 'label',
		hint: 'text-sm text-muted',
		hintLink: 'tooltip link link-info cursor-help',
		required: 'badge badge-soft badge-xs badge-error font-cute',
		validation: 'badge badge-soft badge-sm font-cute',
		count: 'tooltip tabular-nums',
		value: 'font-mono text-xs text-muted',
	},
	input: { base: 'input w-full font-cute' },
	fileInput: { base: 'file-input w-full font-cute' },
	textarea: { base: 'textarea h-24 w-full font-cute' },
	breadcrumbs: { base: 'breadcrumbs text-sm' },
	code: { base: 'inline-flex items-center gap-1 bg-base-300 px-1 font-mono text-xs' },
	disclosure: {
		base: 'mb-6 border-b border-border pb-6 open:[&>summary]:mb-4',
		summary: 'cursor-pointer font-cute text-lg',
	},
	pagination: { base: 'join', item: 'join-item' },
	teaser: { meta: 'text-sm' },
	shape: { box: 'rounded-box', round: 'rounded-full' },
	header: {
		base: 'font-cute',
		weight: { '1': 'font-bold', '2': 'font-bold', '3': '', '4': '', '5': '', '6': '' },
		level: {
			'1': 'text-4xl',
			'2': 'text-3xl',
			'3': 'text-2xl',
			'4': 'text-xl',
			'5': 'text-lg',
			'6': 'text-base',
		},
	},
	paragraph: {
		dim: {
			weakest: 'opacity-95',
			weak: 'opacity-85',
			strong: 'opacity-50',
			strongest: 'opacity-40',
		},
	},
	alert: {
		base: 'alert alert-soft font-cute',
		color: {
			info: 'alert-info',
			success: 'alert-success',
			warning: 'alert-warning',
			error: 'alert-error',
		},
	},
	loading: {
		base: 'loading',
		size: {
			xs: 'loading-xs',
			sm: 'loading-sm',
			md: 'loading-md',
			lg: 'loading-lg',
			xl: 'loading-xl',
		},
		variant: { spinner: 'loading-spinner', dots: 'loading-dots' },
	},
	divider: {
		base: 'divider font-cute mx-auto',
		size: {
			xs: 'w-full max-w-xs',
			sm: 'w-full max-w-sm',
			md: 'w-full max-w-md',
			lg: 'w-full max-w-lg',
			xl: 'w-full max-w-xl',
		},
	},
	avatar: {
		base: 'avatar relative tooltip hover:z-99',
		image: 'rounded-box object-cover',
		placeholder: 'rounded-box bg-base-300 uppercase flex! items-center justify-center',
		indicator: 'tooltip absolute bottom-0 right-0 rounded-selector outline-4 outline-base-100',
		group: 'avatar-group -space-x-3 [&_.avatar]:rounded-box',
		remaining:
			'avatar rounded-box bg-base-300 text-muted font-cute flex! items-center justify-center',
		size: {
			xs: 'size-8 text-xs',
			sm: 'size-12 text-sm',
			md: 'size-16 text-lg',
			lg: 'size-24 text-2xl',
			xl: 'size-32 text-4xl',
		},
		indicatorSize: { xs: 'size-2', sm: 'size-3', md: 'size-4', lg: 'size-7', xl: 'size-9' },
		presence: {
			online: 'bg-success',
			offline: 'bg-base-300',
			away: 'bg-warning',
			busy: 'bg-error',
		},
	},
	key: {
		base: 'kbd px-2 font-mono',
		size: { xs: 'kbd-xs', sm: 'kbd-sm', md: 'kbd-md', lg: 'kbd-lg', xl: 'kbd-xl' },
		textSize: { xs: 'text-xs', sm: 'text-sm', md: 'text-base', lg: 'text-lg', xl: 'text-xl' },
	},
	logo: {
		image: 'object-contain',
		content: 'fill-base-content',
		color: {
			neutral: 'fill-neutral',
			primary: 'fill-primary',
			secondary: 'fill-secondary',
			accent: 'fill-accent',
		},
		size: {
			icon: 'h-4',
			xs: 'h-8',
			sm: 'h-12',
			md: 'h-16',
			lg: 'h-24',
			xl: 'h-32',
			cover: 'h-64',
		},
	},

	btn: {
		base: 'btn font-cute',
		wide: 'btn-wide',
		disabled: 'btn-disabled',
		active: 'btn-active',
		shape: { square: 'btn-square', circle: 'btn-circle' },
		color: {
			neutral: 'btn-neutral',
			primary: 'btn-primary',
			secondary: 'btn-secondary',
			accent: 'btn-accent',
			info: 'btn-info',
			success: 'btn-success',
			warning: 'btn-warning',
			error: 'btn-error',
		},
		size: { xs: 'btn-xs', sm: 'btn-sm', md: 'btn-md', lg: 'btn-lg', xl: 'btn-xl' },
		variant: {
			solid: '',
			outline: 'btn-outline',
			dash: 'btn-dash',
			soft: 'btn-soft',
			ghost: 'btn-ghost',
			link: 'btn-link',
		},
	},
	badge: {
		base: 'badge font-cute',
		color: {
			neutral: 'badge-neutral',
			primary: 'badge-primary',
			secondary: 'badge-secondary',
			accent: 'badge-accent',
			info: 'badge-info',
			success: 'badge-success',
			warning: 'badge-warning',
			error: 'badge-error',
		},
		size: { xs: 'badge-xs', sm: 'badge-sm', md: 'badge-md', lg: 'badge-lg', xl: 'badge-xl' },
		variant: {
			solid: '',
			outline: 'badge-outline',
			dash: 'badge-dash',
			soft: 'badge-soft',
			ghost: 'badge-ghost',
		},
	},
	status: {
		base: 'status',
		pulse: 'motion-safe:animate-ping',
		color: {
			neutral: 'status-neutral',
			primary: 'status-primary',
			secondary: 'status-secondary',
			accent: 'status-accent',
			info: 'status-info',
			success: 'status-success',
			warning: 'status-warning',
			error: 'status-error',
		},
		size: {
			xs: 'status-xs',
			sm: 'status-sm',
			md: 'status-md',
			lg: 'status-lg',
			xl: 'status-xl',
		},
	},
	range: {
		base: 'range w-full!',
		color: {
			neutral: 'range-neutral',
			primary: 'range-primary',
			secondary: 'range-secondary',
			accent: 'range-accent',
			info: 'range-info',
			success: 'range-success',
			warning: 'range-warning',
			error: 'range-error',
		},
		size: { xs: 'range-xs', sm: 'range-sm', md: 'range-md', lg: 'range-lg', xl: 'range-xl' },
	},
	progress: {
		base: 'progress',
		color: {
			neutral: 'progress-neutral',
			primary: 'progress-primary',
			secondary: 'progress-secondary',
			accent: 'progress-accent',
			info: 'progress-info',
			success: 'progress-success',
			warning: 'progress-warning',
			error: 'progress-error',
		},
		size: {
			xs: 'progress-xs',
			sm: 'progress-sm',
			md: 'progress-md',
			lg: 'progress-lg',
			xl: 'progress-xl',
		},
	},
	link: {
		base: 'link font-cute',
		color: {
			neutral: 'link-neutral',
			primary: 'link-primary',
			secondary: 'link-secondary',
			accent: 'link-accent',
			info: 'link-info',
			success: 'link-success',
			warning: 'link-warning',
			error: 'link-error',
		},
		size: { xs: 'link-xs', sm: 'link-sm', md: 'link-md', lg: 'link-lg', xl: 'link-xl' },
	},
	checkbox: {
		base: 'checkbox',
		color: {
			neutral: 'checkbox-neutral',
			primary: 'checkbox-primary',
			secondary: 'checkbox-secondary',
			accent: 'checkbox-accent',
			info: 'checkbox-info',
			success: 'checkbox-success',
			warning: 'checkbox-warning',
			error: 'checkbox-error',
		},
		size: {
			xs: 'checkbox-xs',
			sm: 'checkbox-sm',
			md: 'checkbox-md',
			lg: 'checkbox-lg',
			xl: 'checkbox-xl',
		},
	},
	radio: {
		base: 'radio rounded-selector before:rounded-selector',
		color: {
			neutral: 'radio-neutral',
			primary: 'radio-primary',
			secondary: 'radio-secondary',
			accent: 'radio-accent',
			info: 'radio-info',
			success: 'radio-success',
			warning: 'radio-warning',
			error: 'radio-error',
		},
		size: { xs: 'radio-xs', sm: 'radio-sm', md: 'radio-md', lg: 'radio-lg', xl: 'radio-xl' },
	},
	select: {
		base: 'select w-full font-cute',
		color: {
			neutral: 'select-neutral',
			primary: 'select-primary',
			secondary: 'select-secondary',
			accent: 'select-accent',
			info: 'select-info',
			success: 'select-success',
			warning: 'select-warning',
			error: 'select-error',
		},
		size: {
			xs: 'select-xs',
			sm: 'select-sm',
			md: 'select-md',
			lg: 'select-lg',
			xl: 'select-xl',
		},
	},
} as const;

export const textColors = {
	'base-100': 'text-base-100',
	'base-200': 'text-base-200',
	'base-300': 'text-base-300',
	'base-content': 'text-base-content',
	primary: 'text-primary',
	'primary-content': 'text-primary-content',
	secondary: 'text-secondary',
	'secondary-content': 'text-secondary-content',
	accent: 'text-accent',
	'accent-content': 'text-accent-content',
	neutral: 'text-neutral',
	'neutral-content': 'text-neutral-content',
	info: 'text-info',
	'info-content': 'text-info-content',
	success: 'text-success',
	'success-content': 'text-success-content',
	warning: 'text-warning',
	'warning-content': 'text-warning-content',
	error: 'text-error',
	'error-content': 'text-error-content',
	muted: 'text-muted',
	border: 'text-border',
	focus: 'text-focus',
	'primary-soft': 'text-primary-soft',
	'primary-soft-content': 'text-primary-soft-content',
	'accent-soft': 'text-accent-soft',
	'accent-soft-content': 'text-accent-soft-content',
	'success-soft': 'text-success-soft',
	'success-soft-content': 'text-success-soft-content',
	'success-detail': 'text-success-detail',
	inherit: 'text-inherit',
} as const;
